//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VictimBot.Dialogs.Dialogs.MainChoices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainChoicesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainChoicesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VictimBot.Dialogs.Dialogs.MainChoices.MainChoicesResources", typeof(MainChoicesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a burglary..
        /// </summary>
        public static string Choice_ReportBurglary {
            get {
                return ResourceManager.GetString("Choice_ReportBurglary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review incidents I&apos;ve recorded here..
        /// </summary>
        public static string Choice_ReviewIncidents {
            get {
                return ResourceManager.GetString("Choice_ReviewIncidents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update my personal details..
        /// </summary>
        public static string Choice_UpdatePersonals {
            get {
                return ResourceManager.GetString("Choice_UpdatePersonals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You chose: {0}.
        /// </summary>
        public static string ConfirmChoice {
            get {
                return ResourceManager.GetString("ConfirmChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I wasn&apos;t able to parse that..
        /// </summary>
        public static string OfferOptions_Retry {
            get {
                return ResourceManager.GetString("OfferOptions_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one of the following options, or just say what you&apos;d like to do..
        /// </summary>
        public static string OfferOptionsPreamble {
            get {
                return ResourceManager.GetString("OfferOptionsPreamble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: It is not yet possible to review your recorded burglaries. We&apos;ll come back to that!.
        /// </summary>
        public static string ReviewNotImplemented {
            get {
                return ResourceManager.GetString("ReviewNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, that option was not recognised. Let&apos;s start over..
        /// </summary>
        public static string UnrecognisedOption {
            get {
                return ResourceManager.GetString("UnrecognisedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: It is not yet possible to review and update your personal details. We&apos;ll come back to that!.
        /// </summary>
        public static string UpdatePersonalsNotImplemented {
            get {
                return ResourceManager.GetString("UpdatePersonalsNotImplemented", resourceCulture);
            }
        }
    }
}
