//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VictimBot.Dialogs.Dialogs.ReviewBurglary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReviewBurglaryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReviewBurglaryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VictimBot.Dialogs.Dialogs.ReviewBurglary.ReviewBurglaryResources", typeof(ReviewBurglaryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m ready to tell you what was damaged..
        /// </summary>
        public static string Choice_AddDamagedProperty {
            get {
                return ResourceManager.GetString("Choice_AddDamagedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m ready to look for forensic opportunities..
        /// </summary>
        public static string Choice_AddForensicOpportunities {
            get {
                return ResourceManager.GetString("Choice_AddForensicOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are a few more people involved in this..
        /// </summary>
        public static string Choice_AddInvolved {
            get {
                return ResourceManager.GetString("Choice_AddInvolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m ready with the address..
        /// </summary>
        public static string Choice_AddLocation {
            get {
                return ResourceManager.GetString("Choice_AddLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m ready to record the stolen property..
        /// </summary>
        public static string Choice_AddStolenProperty {
            get {
                return ResourceManager.GetString("Choice_AddStolenProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have some information about the suspects..
        /// </summary>
        public static string Choice_AddSuspects {
            get {
                return ResourceManager.GetString("Choice_AddSuspects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve got details of the victims ready..
        /// </summary>
        public static string Choice_AddVictims {
            get {
                return ResourceManager.GetString("Choice_AddVictims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve got some potential witnesses..
        /// </summary>
        public static string Choice_AddWitnesses {
            get {
                return ResourceManager.GetString("Choice_AddWitnesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;d like to close this report for now..
        /// </summary>
        public static string Choice_CloseReport {
            get {
                return ResourceManager.GetString("Choice_CloseReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;d like to see all my options for this report..
        /// </summary>
        public static string Choice_ReviewAllOptions {
            get {
                return ResourceManager.GetString("Choice_ReviewAllOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve recorded everything there is to add about damage to property..
        /// </summary>
        public static string Complete_AddDamagedProperty {
            get {
                return ResourceManager.GetString("Complete_AddDamagedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s all the forensic opportunities there are..
        /// </summary>
        public static string Complete_AddForensicOpportunities {
            get {
                return ResourceManager.GetString("Complete_AddForensicOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody else was involved - that&apos;s everybody..
        /// </summary>
        public static string Complete_AddInvolved {
            get {
                return ResourceManager.GetString("Complete_AddInvolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location looks ok to me..
        /// </summary>
        public static string Complete_AddLocation {
            get {
                return ResourceManager.GetString("Complete_AddLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s everything that was stolen..
        /// </summary>
        public static string Complete_AddStolenProperty {
            get {
                return ResourceManager.GetString("Complete_AddStolenProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s everything I know about the suspects..
        /// </summary>
        public static string Complete_AddSuspects {
            get {
                return ResourceManager.GetString("Complete_AddSuspects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s all the victims..
        /// </summary>
        public static string Complete_AddVictims {
            get {
                return ResourceManager.GetString("Complete_AddVictims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Those are all the people who might have witnessed it..
        /// </summary>
        public static string Complete_AddWitnesses {
            get {
                return ResourceManager.GetString("Complete_AddWitnesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing was damaged..
        /// </summary>
        public static string Negative_AddDamagedProperty {
            get {
                return ResourceManager.GetString("Negative_AddDamagedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m pretty sure there aren&apos;t any forensic opportunities..
        /// </summary>
        public static string Negative_AddForensicOpportunities {
            get {
                return ResourceManager.GetString("Negative_AddForensicOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody else was involved..
        /// </summary>
        public static string Negative_AddInvolved {
            get {
                return ResourceManager.GetString("Negative_AddInvolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS SHOULD NEVER HAPPEN.
        /// </summary>
        public static string Negative_AddLocation {
            get {
                return ResourceManager.GetString("Negative_AddLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing was stolen..
        /// </summary>
        public static string Negative_AddStolenProperty {
            get {
                return ResourceManager.GetString("Negative_AddStolenProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know anything about the suspects..
        /// </summary>
        public static string Negative_AddSuspects {
            get {
                return ResourceManager.GetString("Negative_AddSuspects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS SHOULD NEVER HAPPEN.
        /// </summary>
        public static string Negative_AddVictims {
            get {
                return ResourceManager.GetString("Negative_AddVictims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m not aware of anybody who might have witnessed the burglary..
        /// </summary>
        public static string Negative_AddWitnesses {
            get {
                return ResourceManager.GetString("Negative_AddWitnesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s add details of any property that was damaged..
        /// </summary>
        public static string Recommendation_AddDamagedProperty {
            get {
                return ResourceManager.GetString("Recommendation_AddDamagedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s think about forensic opportunities..
        /// </summary>
        public static string Recommendation_AddForensicOpportunities {
            get {
                return ResourceManager.GetString("Recommendation_AddForensicOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Were there any other people involved in this? Let&apos;s note down what we know..
        /// </summary>
        public static string Recommendation_AddInvolved {
            get {
                return ResourceManager.GetString("Recommendation_AddInvolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s record the address of the burglary..
        /// </summary>
        public static string Recommendation_AddLocation {
            get {
                return ResourceManager.GetString("Recommendation_AddLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s add details of any stolen property..
        /// </summary>
        public static string Recommendation_AddStolenProperty {
            get {
                return ResourceManager.GetString("Recommendation_AddStolenProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s record any information there is about suspects..
        /// </summary>
        public static string Recommendation_AddSuspects {
            get {
                return ResourceManager.GetString("Recommendation_AddSuspects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s add details of the victims..
        /// </summary>
        public static string Recommendation_AddVictims {
            get {
                return ResourceManager.GetString("Recommendation_AddVictims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s note down details of any potential witnesses..
        /// </summary>
        public static string Recommendation_AddWitnesses {
            get {
                return ResourceManager.GetString("Recommendation_AddWitnesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As the basics are in this report already, let&apos;s look at all your options..
        /// </summary>
        public static string Recommendation_ReviewAllOptions {
            get {
                return ResourceManager.GetString("Recommendation_ReviewAllOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not right now..
        /// </summary>
        public static string Reject_AddDamagedProperty {
            get {
                return ResourceManager.GetString("Reject_AddDamagedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can look into that later..
        /// </summary>
        public static string Reject_AddForensicOpportunities {
            get {
                return ResourceManager.GetString("Reject_AddForensicOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m not ready with details of any other involved people yet..
        /// </summary>
        public static string Reject_AddInvolved {
            get {
                return ResourceManager.GetString("Reject_AddInvolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ll give you the location later..
        /// </summary>
        public static string Reject_AddLocation {
            get {
                return ResourceManager.GetString("Reject_AddLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll come back to that..
        /// </summary>
        public static string Reject_AddStolenProperty {
            get {
                return ResourceManager.GetString("Reject_AddStolenProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can look into that later..
        /// </summary>
        public static string Reject_AddSuspects {
            get {
                return ResourceManager.GetString("Reject_AddSuspects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s look at something else first..
        /// </summary>
        public static string Reject_AddVictims {
            get {
                return ResourceManager.GetString("Reject_AddVictims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll come back to witnesses..
        /// </summary>
        public static string Reject_AddWitnesses {
            get {
                return ResourceManager.GetString("Reject_AddWitnesses", resourceCulture);
            }
        }
    }
}
