//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VictimBot.Dialogs.Dialogs.RecordBurglary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecordNewBurglaryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecordNewBurglaryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VictimBot.Dialogs.Dialogs.RecordBurglary.RecordNewBurglaryResources", typeof(RecordNewBurglaryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m afraid I didn&apos;t understand that..
        /// </summary>
        public static string CannotConfirmIntent {
            get {
                return ResourceManager.GetString("CannotConfirmIntent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not now..
        /// </summary>
        public static string Choice_Back {
            get {
                return ResourceManager.GetString("Choice_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m ready..
        /// </summary>
        public static string Choice_NewReport {
            get {
                return ResourceManager.GetString("Choice_NewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, let&apos;s get started with recording a new burglary report. Please confirm when you&apos;re ready to do that..
        /// </summary>
        public static string ConfirmIntention_Preamble {
            get {
                return ResourceManager.GetString("ConfirmIntention_Preamble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry I didn&apos;t understand - if you&apos;d like to go back to the main menu just say &apos;stop&apos; at any time..
        /// </summary>
        public static string ConfirmIntention_Retry {
            get {
                return ResourceManager.GetString("ConfirmIntention_Retry", resourceCulture);
            }
        }
    }
}
