//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VictimBot.Dialogs.Summaries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IncidentSummaryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IncidentSummaryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VictimBot.Dialogs.Summaries.IncidentSummaryResources", typeof(IncidentSummaryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a new {0} report, and it&apos;s blank..
        /// </summary>
        public static string summary_empty_for_type {
            get {
                return ResourceManager.GetString("summary_empty_for_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a report for the {2} that took place at {0}, {1}..
        /// </summary>
        public static string summary_location_and_timewindow_for_type {
            get {
                return ResourceManager.GetString("summary_location_and_timewindow_for_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a report for the {2} that took place at {0}..
        /// </summary>
        public static string summary_location_for_type {
            get {
                return ResourceManager.GetString("summary_location_for_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to these amounts; {0}.
        /// </summary>
        public static string summary_property_cost_multiple {
            get {
                return ResourceManager.GetString("summary_property_cost_multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string summary_property_cost_X {
            get {
                return ResourceManager.GetString("summary_property_cost_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no estimates).
        /// </summary>
        public static string summary_property_cost_zero {
            get {
                return ResourceManager.GetString("summary_property_cost_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report was started {0}, and completed {1}..
        /// </summary>
        public static string summary_started_and_completed {
            get {
                return ResourceManager.GetString("summary_started_and_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report was started {0}..
        /// </summary>
        public static string summary_started_only {
            get {
                return ResourceManager.GetString("summary_started_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} other people involved: {1}.
        /// </summary>
        public static string summary_X_involved {
            get {
                return ResourceManager.GetString("summary_X_involved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} damaged items, with a total value of: {1}.
        /// </summary>
        public static string summary_X_items_damaged {
            get {
                return ResourceManager.GetString("summary_X_items_damaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} stolen items, with a total value of: {1}.
        /// </summary>
        public static string summary_X_items_stolen_totalling {
            get {
                return ResourceManager.GetString("summary_X_items_stolen_totalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} suspects: {1}.
        /// </summary>
        public static string summary_X_suspects {
            get {
                return ResourceManager.GetString("summary_X_suspects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} vehicles involved: {1}.
        /// </summary>
        public static string summary_X_vehicles {
            get {
                return ResourceManager.GetString("summary_X_vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} victims: {1}.
        /// </summary>
        public static string summary_X_victims {
            get {
                return ResourceManager.GetString("summary_X_victims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} potential witnesses: {1}.
        /// </summary>
        public static string summary_X_witnesses {
            get {
                return ResourceManager.GetString("summary_X_witnesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to burglary.
        /// </summary>
        public static string type_burglary {
            get {
                return ResourceManager.GetString("type_burglary", resourceCulture);
            }
        }
    }
}
