//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VictimBot.Dialogs.Dialogs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VictimBot.Dialogs.Dialogs.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        public static string AbortString {
            get {
                return ResourceManager.GetString("AbortString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remember to dial 999 in an emergency..
        /// </summary>
        public static string EmergenciesAdviceReminder {
            get {
                return ResourceManager.GetString("EmergenciesAdviceReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for contacting the Victim Support Bot. If you&apos;ve been burgled, this bot can help you..
        /// </summary>
        public static string FirstTimeGreeting {
            get {
                return ResourceManager.GetString("FirstTimeGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you&apos;re ready to get started, just say hi..
        /// </summary>
        public static string GetStartedAdvice {
            get {
                return ResourceManager.GetString("GetStartedAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;d rather not continue, just say: stop.
        /// </summary>
        public static string OfferToAbort {
            get {
                return ResourceManager.GetString("OfferToAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m afraid that came through as blank..
        /// </summary>
        public static string ResponseToBlank {
            get {
                return ResourceManager.GetString("ResponseToBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victim Support Bot Service.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
    }
}
