//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VictimBot.Dialogs.Dialogs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VictimBot.Dialogs.Dialogs.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        public static string AbortString {
            get {
                return ResourceManager.GetString("AbortString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Please don&apos;t use this bot to report a crime. Dial 999 in an emergency, and 101 for non-emergencies.**.
        /// </summary>
        public static string EmergenciesAdviceReminder {
            get {
                return ResourceManager.GetString("EmergenciesAdviceReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for contacting the Victim Support Bot. If you&apos;ve been burgled, I can help you to get a head start on the investigation..
        /// </summary>
        public static string FirstTimeGreeting {
            get {
                return ResourceManager.GetString("FirstTimeGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victim Support Bot Service.
        /// </summary>
        public static string FirstTimeSubtitle {
            get {
                return ResourceManager.GetString("FirstTimeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greetings.
        /// </summary>
        public static string FirstTimeTitle {
            get {
                return ResourceManager.GetString("FirstTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you&apos;re ready to get started, just say hi..
        /// </summary>
        public static string GetStartedAdvice {
            get {
                return ResourceManager.GetString("GetStartedAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_add_a_photo_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_add_a_photo_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_add_circle_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_add_circle_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_add_circle_outline_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_add_circle_outline_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_attach_file_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_attach_file_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_backspace_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_backspace_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_block_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_block_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_cake_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_cake_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_clear_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_clear_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_computer_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_computer_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_content_copy_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_content_copy_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_content_paste_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_content_paste_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_create_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_create_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_delete_sweep_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_delete_sweep_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_directions_bike_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_directions_bike_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_directions_car_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_directions_car_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_domain_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_domain_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_done_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_done_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_edit_location_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_edit_location_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_favorite_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_favorite_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_favorite_border_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_favorite_border_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_fingerprint_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_fingerprint_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_format_align_justify_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_format_align_justify_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_format_list_bulleted_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_format_list_bulleted_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_format_list_numbered_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_format_list_numbered_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_forward_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_forward_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_grade_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_grade_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_group_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_group_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_headset_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_headset_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_highlight_off_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_highlight_off_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_home_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_home_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_hourglass_empty_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_hourglass_empty_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_hourglass_full_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_hourglass_full_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_https_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_https_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_info_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_info_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_info_outline_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_info_outline_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_insert_drive_file_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_insert_drive_file_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_language_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_language_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_lightbulb_outline_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_lightbulb_outline_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_lock_open_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_lock_open_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_lock_outline_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_lock_outline_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_mail_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_mail_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_pan_tool_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_pan_tool_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_person_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_person_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_person_outline_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_person_outline_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_phone_android_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_phone_android_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_photo_camera_black_72dp {
            get {
                object obj = ResourceManager.GetObject("ic_photo_camera_black_72dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_photo_library_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_photo_library_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_place_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_place_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_power_settings_new_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_power_settings_new_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_reply_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_reply_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_report_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_report_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_report_problem_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_report_problem_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_save_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_save_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_school_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_school_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_security_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_security_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_shopping_cart_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_shopping_cart_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_speaker_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_speaker_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_stars_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_stars_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_subject_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_subject_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_thumb_down_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_thumb_down_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_thumb_up_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_thumb_up_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_thumbs_up_down_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_thumbs_up_down_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_toc_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_toc_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_undo_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_undo_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_verified_user_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_verified_user_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_videogame_asset_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_videogame_asset_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_visibility_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_visibility_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_watch_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_watch_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_watch_later_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_watch_later_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ic_weekend_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_weekend_black_48dp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;d rather not continue, just say: stop.
        /// </summary>
        public static string OfferToAbort {
            get {
                return ResourceManager.GetString("OfferToAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m afraid that came through as blank..
        /// </summary>
        public static string ResponseToBlank {
            get {
                return ResourceManager.GetString("ResponseToBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victim Support Bot Service.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
    }
}
